CREATE DATABASE EduSys

USE EduSys

CREATE TABLE NhanVien(
	MaNV NVARCHAR(50) NOT NULL,
	MatKhau NVARCHAR(50) NOT NULL,
	HoTen NVARCHAR(50) NOT NULL,
	VaiTro BIT NOT NULL,
	PRIMARY KEY(MaNV)
);

CREATE TABLE ChuyenDe(
	MaCD NVARCHAR(50) NOT NULL,
	TenCD NVARCHAR(50) NOT NULL,
	HocPhi FLOAT NOT NULL,
	ThoiLuong INT NOT NULL,
	Hinh NVARCHAR(50) NOT NULL,
	MoTa NVARCHAR(255) NOT NULL,
	PRIMARY KEY(MaCD)
);

CREATE TABLE KhoaHoc(
	MaKH INT IDENTITY(1,1) NOT NULL,
	MaCD NVARCHAR(50) NOT NULL,
	HocPhi FLOAT NOT NULL,
	ThoiLuong INT NOT NULL,
	NgayKG DATE NOT NULL,
	GhiChu NVARCHAR(50) NOT NULL,
	MaNV NVARCHAR(50) NOT NULL,
	NgayTao DATE NOT NULL,
	PRIMARY KEY(MaKH),
	FOREIGN KEY(MaCD) REFERENCES ChuyenDe(MaCD) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY(MaNV) REFERENCES NhanVien(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE NguoiHoc(
	MaNH NVARCHAR(50) NOT NULL,
	HoTen VARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh BIT NOT NULL,
	DienThoai NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	GhiChu NVARCHAR(255) NOT NULL,
	MaNV NVARCHAR(50) NOT NULL,
	NgayDK DATE NOT NULL,
	PRIMARY KEY(MaNH),
	FOREIGN KEY(MaNV) REFERENCES NhanVien(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE HocVien(
    MaHV INT IDENTITY(1,1) NOT NULL,
    MaKH INT NOT NULL,
    MaNH NVARCHAR(50) NOT NULL,
    Diem FLOAT NOT NULL,
    PRIMARY KEY(MaHV),
    FOREIGN KEY(MaNH) REFERENCES NguoiHoc(MaNH) ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY(MaKH) REFERENCES KhoaHoc(MaKH) ON DELETE CASCADE ON UPDATE NO ACTION
);

--Report: MaNH, HoTen, Diem
CREATE PROCEDURE sp_BangDiem(@MaKH INT)
AS BEGIN
	SELECT
		nh.MaNH,
		nh.HoTen,
		hv.Diem
	FROM HocVien hv JOIN NguoiHoc nh ON nh.MaNH=hv.MaNH
	WHERE hv.MaKH=@MaKH
	ORDER BY hv.Diem DESC 
END

--Report: TenCD, SoHocVien, Diem
CREATE PROCEDURE sp_ThongKeDiem
AS BEGIN
	SELECT
		TenCD ChuyenDe,
		COUNT(MaHV) SoHV,
		MIN(Diem) ThapNhat,
		MAX(Diem) CaoNhat,
		AVG(Diem) TrungBinh
	FROM KhoaHoc kh JOIN HocVien hv ON kh.MaKH=hv.MaKH
					JOIN ChuyenDe cd ON cd.MaCD=kh.MaCD
	GROUP BY TenCD
END

--Report: TenCD, SoHocVien, DoanhThu,...
CREATE PROCEDURE sp_ThongKeDoanhThu(@Year INT)
AS BEGIN
	SELECT
		cd.TenCD TenChuyenDe,
		COUNT(DISTINCT kh.MaKH) SoKH,
		COUNT(hv.MaHV) SoHV,
		SUM(kh.HocPhi) DoanhThu,
		MIN(kh.HocPhi) ThapNhat,
		MAX(kh.HocPhi) CaoNhat,
		AVG(kh.HocPhi) TrungBinh
	FROM KhoaHoc kh JOIN HocVien hv ON kh.MaKH=hv.MaKH
					JOIN ChuyenDe cd ON cd.MaCD=kh.MaCD
	WHERE YEAR(NgayKG) = @Year
	GROUP BY TenCD
END

--Report: Nam, SoLuong, 
CREATE PROCEDURE sp_ThongKeNguoiHoc
AS BEGIN
	SELECT
		YEAR(NgayDK) Nam,
		COUNT(*) SoLuong,
		MIN(NgayDK) DauTien,
		MAX(NgayDK) CuoiCung
	FROM NguoiHoc
	GROUP BY NgayDK
END